version: 0.2
os: linux
files:
  - source: /app.js
    destination: /var/www/html/
  - source: /appform.html
    destination: /var/www/html/
  - source: /index.html
    destination: /var/www/html/
  - source: /page.html
    destination: /var/www/html/ 
hooks:
   BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

